[package]
name = "wgpu-mine"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.15.0"
flume = "0.11.0"
pollster = "0.3.0"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"

tracing = "0.1.40"
tracing-subscriber = "0.3.18"
wgpu = "0.19.4"
