[workspace]
resolver = "2"
members = [
    "rust-namer",
    "miner"
]

# [miner.profile.release]
# opt-level = 3
# codegen-units = 1
# # panic = "abort"
# debug = true
# strip = false
# lto = true
# overflow-checks = false
